export const ENV = {
  SUPABASE_URL: import.meta.env.VITE_SUPABASE_URL as string,
  SUPABASE_ANON_KEY: import.meta.env.VITE_SUPABASE_ANON_KEY as string,
  FIREBASE_API_KEY: import.meta.env.VITE_FIREBASE_API_KEY as string,
  FIREBASE_AUTH_DOMAIN: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN as string,
  FIREBASE_PROJECT_ID: import.meta.env.VITE_FIREBASE_PROJECT_ID as string,
  FIREBASE_STORAGE_BUCKET: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET as string,
  FIREBASE_MESSAGING_SENDER_ID: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID as string,
  FIREBASE_APP_ID: import.meta.env.VITE_FIREBASE_APP_ID as string,
  OCR_BACKEND_URL: import.meta.env.VITE_OCR_BACKEND_URL as string,
  APP_NAME: (import.meta.env.VITE_APP_NAME as string) || 'NTT DATA Bank',
  APP_VERSION: (import.meta.env.VITE_APP_VERSION as string) || '1.0.0',
  OCR_CONFIDENCE_THRESHOLD: Number(import.meta.env.VITE_OCR_CONFIDENCE_THRESHOLD) || 0.85,
  AML_RISK_THRESHOLD: Number(import.meta.env.VITE_AML_RISK_THRESHOLD) || 70,
  MAX_FILE_SIZE_MB: Number(import.meta.env.VITE_MAX_FILE_SIZE_MB) || 10,
  ALLOWED_FILE_TYPES: ((import.meta.env.VITE_ALLOWED_FILE_TYPES as string) || 'image/jpeg,image/png,application/pdf').split(','),
  SESSION_TIMEOUT_MINUTES: Number(import.meta.env.VITE_SESSION_TIMEOUT_MINUTES) || 30,
  ENVIRONMENT: (import.meta.env.VITE_ENVIRONMENT as string) || 'production',
};
